package.json
src/App.vue
src/components/HistoryPage.vue
src/components/SendPage.vue
src/main.js
src/router/index.js
src/store/accounts/accounts.js
test/unit/specs/HistoryPage.spec.js

Transaction history

---

src/App.vue
src/components/AccountChooser.vue
src/components/ImportWallet.vue
src/components/ModalComponent.vue
src/components/NewAccountModal.vue
src/components/NewWallet.vue
src/components/TransactionComponent.vue
src/css/_settings.scss
src/store/accounts/accounts.js
test/unit/specs/AccountChooser.spec.js
test/unit/specs/Accounts.store.spec.js
test/unit/specs/ImportWallet.spec.js

User can create new accounts from HD wallet and switch the active account.

Account chooser

---

package.json
src/components/ExportToJson.vue
src/components/ImportWallet.vue
src/components/ResendModal.vue
src/components/SendPage.vue
test/unit/specs/AccountChooser.spec.js
test/unit/specs/ExportToJSON.spec.js
test/unit/specs/ImportWallet.spec.js
test/unit/specs/SentEther.spec.js
yarn.lock

Validation for ExportToJson.vue, ResendModal.vue, ImportWallet.vue.
ImportWallet.vue  has error in tests.

Validation

---

test/unit/ethereumWalletMock.js
test/unit/specs/ExportToJSON.spec.js
test/unit/specs/HistoryPage.spec.js
test/unit/specs/RecievePage.spec.js

Add ethereum wallet mock for tests

Ethereum wallet mock

---

src/components/AccountChooser.vue
src/components/CustomProviderModal.vue
src/components/ExportToJson.vue
src/components/HistoryPage.vue
src/components/ImportWallet.vue
src/components/InfoBar.vue
src/components/NewAccountModal.vue
src/components/NewWallet.vue
src/components/ReceivePage.vue
src/components/TokensPage.vue
src/store/accounts/accounts.js
src/store/tokens/tokens.js
src/store/web3/web3.js
test/unit/specs/ImportWallet.spec.js
test/unit/specs/Tokens.store.spec.js

Add user notifications and error handling for external API

Add error handling for external API and user notification for errors

---

src/components/ui/form/VInput.vue
test/unit/specs/components/ui/form/VInput.spec.js

Add input component

---

src/components/pages/ImportWallet.vue
src/services/addressWallet.js
test/unit/specs/components/pages/ImportWallet.spec.js

Allow importing a view-only Ethereum address

Address import

---

src/components/ExportToJson.vue
src/components/NewAccountModal.vue
src/components/bar/CustomProviderModal.vue
src/components/bar/InfoBar.vue
src/components/pages/Send.vue
src/components/pages/Settings.vue
src/components/ui/ModalComponent.vue
src/components/ui/form/VButton.vue
src/components/ui/form/VForm.vue
src/components/ui/form/VInput.vue
test/unit/specs/components/ui/form/VButton.spec.js
test/unit/specs/components/ui/form/VInput.spec.js

Send transaction validation and feedback

Send transaction validation and feedback

---

package.json
src/components/NewAccountModal.vue
src/components/bar/CustomProviderModal.vue
src/components/importWallet/ImportFromJson.vue
src/components/importWallet/ImportFromPrivateKey.vue
src/components/importWallet/ImportFromPublicKey.vue
src/components/importWallet/ImportFromSeed.vue
src/components/pages/ImportWallet.vue
src/components/pages/Send.vue
src/components/ui/VList.vue
src/components/ui/VModal.vue
src/components/ui/form/VButton.vue
src/components/ui/form/VForm.vue
src/components/ui/form/VInput.vue
test/unit/jest.conf.js
test/unit/specs/components/importWallet/ImportFromJson.spec.js
test/unit/specs/components/importWallet/ImportFromPrivateKey.spec.js
test/unit/specs/components/importWallet/ImportFromPublicKey.spec.js
test/unit/specs/components/importWallet/ImportFromSeed.spec.js
test/unit/specs/components/pages/ImportWallet.spec.js
test/unit/specs/components/ui/VList.spec.js
test/unit/specs/components/ui/form/VButton.spec.js
test/unit/specs/components/ui/form/VInput.spec.js
test/unit/specs/components/ui/form/VSelect.spec.js
yarn.lock

Split and refactor import wallet

Split and refactor import wallet

---

src/components/pages/Send.vue
src/validation/hex.js
src/validation/index.js

Fix validation bug

---

package.json
src/class/index.js
src/class/provider/DebounceProvider.js
src/class/provider/index.js
src/class/provider/providerFactory.js
src/components/modal/TransactionModal.vue
src/components/pages/Send.vue
src/store/accounts/accounts.js
src/store/web3/web3.js
yarn.lock

Add debounce for web3 provider

Add debounce for web3 provider

---

src/App.vue
src/class/EventEmitter.js
src/class/error/NotificationError.js
src/class/error/index.js
src/class/index.js
src/class/provider/index.js
src/class/provider/providerFactory.js
src/class/provider/providerMixin.js
src/components/NewAccountModal.vue
src/components/bar/AccountChooser.vue
src/components/bar/CustomProviderModal.vue
src/components/bar/ProviderSelect.vue
src/components/importWallet/ImportFromJson.vue
src/components/importWallet/ImportFromPrivateKey.vue
src/components/importWallet/ImportFromPublicKey.vue
src/components/importWallet/ImportFromSeed.vue
src/components/pages/Settings.vue
src/mixins/error.js
src/mixins/errorHandler.js
src/services/storage/LocalStorage.js
src/store/accounts/accounts.js
src/store/errors/errors.js
src/store/index.js
src/store/tokens/tokens.js
src/store/web3/web3.js
test/unit/specs/services/storage/LocalStorage.spec.js
test/unit/specs/store/Web3.spec.js

Fix error handling

---

src/store/web3/web3.js

Fix bug in initializing web3 store

Fix bug in initializing web3 store

---

src/class/Transaction.js
src/components/ResendModal.vue
src/components/Transaction.vue
src/components/pages/Send.vue
src/store/accounts/accounts.js
test/unit/specs/class/Transaction.spec.js
test/unit/specs/components/pages/Send.spec.js

Fix send page after adding Transaction class

Fix send page after adding Transaction class

---

src/components/pages/Send.vue
src/components/ui/form/VForm.vue
test/unit/specs/components/pages/Send.spec.js

Fix amount/price sync and validation

Fix amount/price sync and validation

---

src/components/ExportToJson.vue
src/components/importWallet/ImportFromJson.vue
src/components/ui/form/VForm.vue
src/store/accounts/accounts.js
test/unit/specs/store/Accounts.spec.js

Remove unnecessary password field in import/export to json

Remove unnecessary password field in import/export to json

---

src/components/bar/CustomProviderModal.vue
src/components/pages/Send.vue
src/components/ui/VModal.vue
src/components/ui/form/VInput.vue
src/components/ui/form/VSelect.vue
src/css/_settings.scss
src/css/buttons.scss
src/css/transitions.scss
test/unit/specs/components/ui/form/VInput.spec.js

Send form style

---

config/index.js
src/components/TwoFactorAuthSettings.vue
src/components/modal/TwoFactorAuthModal.vue
src/components/pages/Login.vue
src/components/pages/Settings.vue
src/components/ui/form/VSelect.vue
src/config/dev.env.js
src/config/index.js
src/config/prod.env.js
src/mixins/modal.js
src/services/user.js
src/store/accounts/accounts.js
test/unit/specs/components/TwoFactorAuthSettings.spec.js
test/unit/specs/components/__snapshots__/TwoFactorAuthSettings.spec.js.snap
test/unit/specs/components/modal/TwoFactorAuthModal.spec.js
test/unit/specs/components/modal/__snapshots__/TwoFactorAuthModal.spec.js.snap
test/unit/specs/components/pages/Login.spec.js
test/unit/specs/components/pages/Settings.spec.js
test/unit/specs/components/pages/__snapshots__/Login.spec.js.snap
test/unit/specs/components/pages/__snapshots__/Settings.spec.js.snap
test/unit/specs/mixins/modal.spec.js
test/unit/specs/store/Accounts.spec.js

Запросы оставил пока замокаными, вылезла проблема с CORS при запросах на дев сервер.

 Added settings for two factor auth via OTP

---

src/components/ExportToPrivateKey.vue
src/components/modal/PasswordModal.vue

Fast fix export processing with incorrect password

Fix export processing with incorrect password

---

src/components/bar/CustomProviderModal.vue
src/components/ui/form/VForm.vue
src/store/web3/web3.js

Add provider verification

---

src/components/SearchInput.vue
src/components/pages/Base.vue
src/components/pages/Tokens.vue
src/img/plus.svg
src/utils/testUtils.js
test/unit/specs/components/pages/Base.spec.js
test/unit/specs/components/pages/Login.spec.js
test/unit/specs/components/pages/Tokens.spec.js
test/unit/specs/components/pages/__snapshots__/Tokens.spec.js.snap

Fix the search in the list of tokens

Fix the search in the list of tokens

---

src/components/pages/Tokens.vue
src/services/index.js
src/store/tokens/tokens.js
test/unit/__mocks__/services/ethplorer.js
test/unit/specs/components/pages/Tokens.spec.js
test/unit/specs/components/pages/__snapshots__/Tokens.spec.js.snap
test/unit/specs/store/Tokens.spec.js

Allow removing tokens from "Your Tokens" list on Tokens page

Add removing tokens

---

src/components/pages/Tokens.vue
src/store/tokens/tokens.js
test/unit/specs/components/pages/Tokens.spec.js
test/unit/specs/store/Tokens.spec.js

Fix the loader and the process of removing tokens

Fix the loader and the process of removing tokens

---

src/components/pages/Tokens.vue
src/store/tokens/tokens.js
test/unit/specs/components/pages/Tokens.spec.js
test/unit/specs/store/Tokens.spec.js

Fix receipt of tokens from a remote service

Fix receipt of tokens from a remote service

---

src/components/NewAccountModal.vue

Change the processing of adding a new account

Change the processing of adding a new account

---

src/components/bar/AccountChooser.vue
src/components/importWallet/ImportFromPublicKey.vue
src/components/importWallet/ImportFromSeed.vue
src/store/accounts/accounts.js
test/unit/specs/store/Accounts.spec.js

Add import accounts from the hd wallet

Add import accounts from the hd wallet

---

src/components/bar/CustomProviderModal.vue

Fix form validation in the provider modal

Fix form validation in the provider modal

---

test/unit/specs/components/pages/Send.spec.js

Fix an error in the send test

---

test/unit/specs/store/Accounts.spec.js

Fix error in the accounts store test

Fix error in the accounts store test

---

src/store/accounts/accounts.js

Fix the display of notifications for user accounts

Fix the display of notifications for user accounts

---

.travis.yml

- Added deploy section.
- All vars in the deploy section are encrypted with travis encrypt

New .travis.yml

---

src/components/importWallet/ImportFromPrivateKey.vue
src/components/importWallet/ImportFromPublicKey.vue
src/components/importWallet/ImportFromSeed.vue

Fix incorrect private key for importing account

Fix incorrect private key for importing account

---

package.json

Fix prettier pre-commit hook

---

src/components/pages/Send.vue
src/components/ui/form/VInputAddress.vue
src/store/transactions/transactions.js
src/validation/ensOrAddress.js

Fix of sending a transaction

---

src/components/pages/Send.vue
test/unit/specs/components/pages/Send.spec.js

Adds a button to send the entire balance to SendPage

Entire balance

---

src/components/NavSidebar.vue
src/components/bar/CustomProviderModal.vue
src/components/bar/ProviderSelect.vue
src/mixins/net.js
src/services/user.js
src/store/accounts/accounts.js
test/unit/__mocks__/services/user.js
test/unit/specs/components/bar/CustomProviderModal.spec.js
test/unit/specs/components/bar/ProviderSelect.spec.js

Fix interaction with remote storage

Fix interaction with remote storage

---

src/components/modal/LoginModal.vue
src/services/user.js
src/store/accounts/accounts.js
test/unit/specs/services/user.spec.js
test/unit/specs/store/Accounts.spec.js

Fix a token request for otp login

Fix a token request for otp login

---

src/components/modal/PasswordModal.vue
src/components/ui/form/VPassword.vue
src/store/transactions/transactions.js
test/unit/specs/components/modal/PasswordModal.spec.js
test/unit/specs/store/Transactions.spec.js

Fix password validation and transaction getters bug

Fix password validation and transaction getters bug

---

src/components/pages/Send.vue
src/services/gas-price.js
test/unit/specs/components/pages/Send.spec.js

Fix price input bug with zero eth price

Fix price input bug with zero eth price

---

src/components/pages/Send.vue
test/unit/specs/components/pages/Send.spec.js

Fix the update nonce when the network changes

Fix the update nonce when the network changes

---

src/class/wallet.js
src/components/pages/Send.vue
src/store/transactions/transactions.js
test/unit/fixtures/accounts.js
test/unit/specs/class/Wallet.spec.js
test/unit/specs/components/pages/Send.spec.js
test/unit/specs/store/Transactions.spec.js

Fix send transaction process

---

src/components/pages/Send.vue
test/unit/specs/components/pages/Send.spec.js

Fix nonce calculation on the send page

Fix nonce calculation on the send page

---

src/config/dev.env.js
src/config/test.env.js

Fix url for getting token images

Fix url for getting token images

---

src/class/provider/DebounceProvider.js
test/unit/specs/class/provider/DebounceProvider.spec.js

Fix buffer bug in debounce provider

Fix buffer bug in debounce provider

---

src/store/accounts/accounts.js
test/unit/specs/store/Accounts.spec.js

Fix the logout by resetting vuex via a reload

Fix the logout by resetting vuex via a reload

---

src/class/wallet.js
src/components/ExportToJson.vue
src/components/ExportToPrivateKey.vue
test/unit/fixtures/accounts.js
test/unit/specs/class/Wallet.spec.js
test/unit/specs/components/ExportToJson.spec.js
test/unit/specs/components/ExportToPrivateKey.spec.js

Fix export to private key and json

Fix export to private key and json

---

src/store/accounts/accounts.js

Fix initialization of tokens

---

package.json
src/store/transactions/transactions.js

Also adds `npx` into package scripts

Fixes send page breaking issue

---

src/store/web3/web3.js

Fix initialization of the web3 provider

Fix initialization of the web3 provider

---

package.json
src/store/web3/web3.js

Add a provider availability check before destroying
Remove npx

Add a provider availability check before destroying

---

.eslintrc
src/class/Token.js
src/components/pages/Send.vue
src/components/ui/form/VSelect.vue
src/store/tokens/getters.js
test/unit/specs/class/Token.spec.js
test/unit/specs/components/modal/AddTokenModal.spec.js
test/unit/specs/store/tokens/getters.spec.js

Add rule to eslint for alias imports

Fix send page currencies select issue

---

src/components/pages/Send.vue
src/store/transactions/transactions.js

Fix mutations in the transaction store

Fix mutations in the transaction store

---

src/store/accounts/accounts.js
test/unit/specs/store/Accounts.spec.js

Fix password validation for a public account

Fix password validation for a public account

---

src/utils/web3.js

Fix the bug with the provider in the web3 instance

Fix the bug with the provider in the web3 instance

---

src/store/transactions/actions.js
test/unit/specs/store/transactions/actions.spec.js

Fix the error handler when sending transactions

Fix the error handler when sending transactions

---

src/class/erc20.js
src/class/index.js
src/utils/web3.js

Fix send token error

---

src/components/pages/Send.vue
src/css/typography.scss
test/unit/specs/components/pages/Send.spec.js
test/unit/specs/components/pages/__snapshots__/Send.spec.js.snap

Add resolved ENS address caption under address input on Send page

---

src/components/NavSidebar.vue
src/components/importWallet/ImportFromJson.vue
src/components/importWallet/ImportFromPrivateKey.vue
src/components/importWallet/ImportFromPublicKey.vue
src/components/importWallet/ImportFromSeed.vue
src/components/modal/PasswordModal.vue
src/components/pages/Home.vue
src/components/ui/PageLoader.vue
src/store/web3/actions.js
test/e2e/fixtures/accounts/index.js
test/e2e/fixtures/addressinfo/31ea8.json
test/e2e/fixtures/addressinfo/b14ab.json
test/e2e/fixtures/keystore/account_import.json
test/e2e/specs/import_wallet.spec.js
test/e2e/support/commands.js
test/unit/specs/components/__snapshots__/NavSidebar.spec.js.snap
test/unit/specs/components/importWallet/__snapshots__/ImportFromJson.spec.js.snap
test/unit/specs/components/importWallet/__snapshots__/ImportFromPrivateKey.spec.js.snap
test/unit/specs/components/importWallet/__snapshots__/ImportFromSeed.spec.js.snap
test/unit/specs/components/ui/__snapshots__/PageLoader.spec.js.snap
test/unit/specs/store/web3/actions.spec.js

Add e2e tests for importing a wallet

Add e2e tests for importing a wallet

---

.eslintrc
src/components/ChangePasswordSettings.vue
src/components/TwoFactorAuthSettings.vue
src/components/modal/TwoFactorAuthModal.vue
src/components/pages/NewWallet.vue
src/components/pages/Settings.vue
src/components/ui/form/VInput.vue
src/components/ui/form/VPassword.vue
test/e2e/specs/import_wallet.spec.js
test/e2e/specs/new_wallet.spec.js
test/e2e/specs/user_settings.spec.js
test/e2e/support/commands.js
test/unit/specs/components/__snapshots__/ChangePasswordSettings.spec.js.snap
test/unit/specs/components/__snapshots__/TwoFactorAuthSettings.spec.js.snap
test/unit/specs/components/modal/__snapshots__/TwoFactorAuthModal.spec.js.snap
test/unit/specs/components/pages/Settings.spec.js
test/unit/specs/components/pages/__snapshots__/Settings.spec.js.snap
test/unit/specs/components/ui/form/VInput.spec.js

Add e2e tests for user settings

Add e2e tests for user settings

---

package.json
src/components/Transaction.vue
src/main.js
src/utils/date.js
test/unit/specs/components/Transaction.spec.js
test/unit/specs/utils/date.spec.js
yarn.lock

Replace moment with dayjs

---

src/components/TokensList.vue
src/components/pages/Home.vue
src/store/tokens/actions.js
src/store/tokens/getters.js
test/unit/fixtures/tokens.js
test/unit/specs/components/TokensList.spec.js
test/unit/specs/store/tokens/getters.spec.js

Add some semantic and helpfull getters for tokens
Update TokensList component logic for removing tokens

Visually split tokens on home page and improve removing logic for tokens lists

---

src/class/provider/DebounceProvider.js
src/store/transactions/actions.js
src/store/web3/actions.js
src/store/web3/mutations.js
test/unit/specs/store/transactions/actions.spec.js
test/unit/specs/store/web3/actions.spec.js
test/unit/specs/store/web3/mutations.spec.js
test/unit/specs/utils/keystore.spec.js

Fix errors when processing incoming transactions

Fix errors when processing incoming transactions

---

src/class/Transaction.js
src/class/index.js
src/class/transaction/TransactionFactory.js
src/store/transactions/actions.js
src/store/transactions/getters.js
test/unit/fixtures/transactions.js
test/unit/specs/store/transactions/actions.spec.js
test/unit/specs/store/transactions/getters.spec.js

Fix incoming transaction data in history

Fix for incoming transaction processing

---

package.json
src/constants/index.js
test/unit/specs/store/web3/getters.spec.js
yarn.lock

Switch network URLs to Endpass nodes

Switch network URLs to Endpass nodes

---

src/class/provider/providerFactory.js
src/class/transaction/TransactionFactory.js
src/store/transactions/actions.js
src/store/web3/actions.js
test/e2e/fixtures/transactions/index.js
test/e2e/specs/transactions_history.js
test/unit/fixtures/transactions.js
test/unit/specs/store/transactions/actions.spec.js
test/unit/specs/store/web3/actions.spec.js

Fix bug in history page and pending balance

Fix bug in history page and pending balance

---

src/class/address.js
src/class/hardwareWallet/LedgerWallet.js
src/class/hardwareWallet/TrezorWallet.js
src/constants/index.js
src/services/hardware.js
src/store/accounts/actions.js
src/store/accounts/index.js
src/store/accounts/mutations-types.js
src/store/accounts/mutations.js

Get hardware wallets from xpub and save xpub to server

Get hardware wallets from xpub and save xpub to server

---

src/components/importWallet/ImportFromHardware/HardwareList.vue

Fix popup window for Trezor wallet

Fix popup window for Trezor wallet

---

src/components/pages/Settings.vue
src/store/user/actions.js
src/store/user/mutations.js
test/unit/specs/components/pages/Settings.spec.js
test/unit/specs/store/user/actions.spec.js

Fix bug with fiat currency for new account

Fix bug with fiat currency for new account

---

src/class/address.js
src/class/hardwareWallet/LedgerWallet.js
src/class/hardwareWallet/TrezorWallet.js
src/class/wallet.js
src/components/VerifyMessage.vue
src/components/modal/PasswordModal.vue
src/components/pages/Home.vue
test/unit/specs/components/pages/Home.spec.js
test/unit/specs/store/accounts/getters.spec.js

Fix hardware

---

src/class/provider/ProviderFactory.js
src/class/transaction/TransactionFactory.js
src/class/web3/Web3Factory.js
src/constants/index.js
src/store/transactions/actions.js
src/store/web3/actions.js
test/unit/specs/store/transactions/actions.spec.js

Improve web3 provider fallback

Improve web3 provider fallback

---

src/constants/index.js

Add network URLs for a seamless transition

Add network URLs for a seamless transition

---

config/dev.env.js
config/index.js
config/prod.env.js
config/test.env.js
src/class/singleton/httpIdentity.js
src/components/bar/InfoBar.vue
src/constants/index.js
src/services/auth.js
src/services/user.js
src/store/accounts/getters.js
src/store/tokens/actions.js
src/store/user/actions.js
src/store/web3/actions.js
test/e2e/fixtures/identity/user.json
test/e2e/specs/log_in.spec.js
test/e2e/specs/new_wallet.spec.js
test/e2e/specs/user_settings.spec.js
test/e2e/support/commands.js
test/unit/fixtures/accounts.js
test/unit/fixtures/identity.js
test/unit/mocks/services/user.js
test/unit/specs/class/singleton/httpIdentity.spec.js
test/unit/specs/services/auth.spec.js
test/unit/specs/services/user.spec.js
test/unit/specs/store/tokens/actions.spec.js
test/unit/specs/store/user/actions.spec.js
test/unit/specs/store/web3/actions.spec.js

Switch to the identity API v1.1

Switch to the identity API v1.1

---

src/components/modal/AddTokenModal.vue
test/e2e/fixtures/tokeninfo/index.js
test/e2e/specs/tokens.spec.js
test/unit/mocks/class/erc20.js
test/unit/specs/components/modal/AddTokenModal.spec.js
test/unit/specs/components/modal/__snapshots__/AddTokenModal.spec.js.snap

Fix add custom token with missing token info

Fix add custom token with missing token info

---

src/schema/cryptoData.js
src/schema/identity/index.js
src/schema/identity/network.js
src/schema/identity/otp.js
src/schema/identity/settings.js
src/schema/identity/token.js
src/schema/index.js
src/schema/v3Keystore.js
src/services/cryptoData.js
src/services/user.js
test/e2e/fixtures/identity/user.json
test/unit/fixtures/identity.js
test/unit/fixtures/tokens.js
test/unit/mocks/schema/index.js
test/unit/specs/schema/index.spec.js

Add schema validation to user service

Add schema validation to user service

---

src/class/hardwareWallet/index.js
src/class/index.js
src/class/wallet.js
src/class/web3/Web3Factory.js

Fix circular dependency in the wallet class

Fix circular dependency in the wallet class

---

build/webpack.dev.conf.js
build/webpack.prod.conf.js
package.json
yarn.lock

~Add webpack plugin for normal lodash tree shaking~

Update bundle analyzer and configure it modes

---

src/components/bar/CustomProviderModal.vue
test/unit/specs/components/bar/CustomProviderModal.spec.js
test/unit/specs/services/cryptoData.spec.js

Fix adding a user network provider

Fix adding a user network provider

---

.babelrc
package.json

Drop IE support

---

src/class/transaction/Transaction.js
src/components/Transaction.vue
src/store/transactions/mutations.js
test/e2e/specs/transactions_history.js
test/unit/specs/class/Transaction.spec.js
test/unit/specs/components/__snapshots__/Transaction.spec.js.snap

Fix update transaction state in history page

---

src/schema/identity/settings.js
test/e2e/fixtures/identity/user.json
test/unit/fixtures/identity.js
test/unit/specs/schema/index.spec.js

Fix identity schema after API update

Fix identity schema after API update

---

src/class/provider/ProviderFactory.js
src/class/web3/Web3Factory.js
src/constants/index.js
src/store/plugins/web3.js

Fix web3 provider initialization

Fix web3 provider initialization

---

build/check-versions.js
build/style-loaders.js
build/vue-loader.conf.js
build/webpack.base.conf.js
build/webpack.dev.conf.js
build/webpack.prod.conf.js
package.json
yarn.lock

- Moved reusable code to utils

(refactor): build utils from package

---

package.json
yarn.lock

Downgrade @endpass/connect

---

package.json
yarn.lock

chore: update connect and class to latest version

fix: logout fix

---

src/components/modal/TwoFactorAuthModal.vue

Fix otp enable qr

---

src/components/NavSidebar.vue

feat: remove dApp link from sidebar

---

package.json
src/services/user.js
tests/e2e/support/commands/login.js
tests/unit/specs/services/user.spec.js
yarn.lock

Fix account info for re-import when public exists

Fix account info for re-import when public exists
